#!/usr/bin/env python3
"""Interactive environment setup with enhanced security."""

import getpass
import hashlib
import os
import secrets

from cryptography.fernet import Fernet
from passlib.context import CryptContext


def main():
    print("=== VFS-Bot Environment Setup ===\n")
    print("⚠️  GÜVENLIK UYARISI: Bu script .env dosyası oluşturacak.")
    print("    Dosyayı git'e commit etmemeye dikkat edin!")
    print("    .env dosyası hassas bilgiler içerir ve .gitignore'da olmalıdır.\n")

    # Generate encryption key first
    encryption_key = Fernet.generate_key().decode()

    # Generate other security keys
    # token_urlsafe(48) generates 48 bytes = 64 base64 characters
    api_secret = secrets.token_urlsafe(48)  # 64 character output
    api_key_salt = secrets.token_urlsafe(32)  # 43 character output
    vfs_encryption_key = secrets.token_urlsafe(32)  # 43 character output

    # Get user input
    vfs_email = input("VFS Email: ")
    vfs_password = getpass.getpass("VFS Password: ")
    admin_username = input("Admin Username [admin]: ") or "admin"
    admin_password = getpass.getpass("Admin Password: ")

    # Hash admin password for secure storage
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    admin_hash = pwd_context.hash(admin_password)

    # Encrypt VFS password with Fernet for secure storage
    cipher = Fernet(encryption_key.encode())
    encrypted_vfs_password = cipher.encrypt(vfs_password.encode()).decode()

    # Generate secure database password
    db_password = secrets.token_urlsafe(24)

    # Write .env file
    # Note: VFS_PASSWORD is encrypted using Fernet encryption for security
    # The application will decrypt it at startup using the ENCRYPTION_KEY
    env_content = f"""# VFS-Bot Environment Configuration
# Generated by setup_environment.py
# ⚠️ DO NOT COMMIT THIS FILE TO VERSION CONTROL!
# This file contains sensitive credentials and should be in .gitignore

# ===========================================
# VFS Credentials
# ===========================================
VFS_EMAIL={vfs_email}
# Note: VFS_PASSWORD is encrypted with Fernet for security
# The application automatically decrypts it using ENCRYPTION_KEY
VFS_PASSWORD={encrypted_vfs_password}
VFS_PASSWORD_ENCRYPTED=true

# ===========================================
# Encryption Keys (CRITICAL - DO NOT SHARE)
# ===========================================
# Used for encrypting sensitive data in the database and sessions
ENCRYPTION_KEY={encryption_key}
VFS_ENCRYPTION_KEY={vfs_encryption_key}

# ===========================================
# API Security
# ===========================================
# 64-character secret key for JWT token signing
API_SECRET_KEY={api_secret}
# 43-character salt for API key hashing
API_KEY_SALT={api_key_salt}

# ===========================================
# Admin Credentials
# ===========================================
ADMIN_USERNAME={admin_username}
# Password is bcrypt hashed for secure storage
ADMIN_PASSWORD={admin_hash}

# ===========================================
# Environment
# ===========================================
ENV=production

# ===========================================
# Database (PostgreSQL)
# ===========================================
DATABASE_URL=postgresql://vfs_bot:{db_password}@localhost:5432/vfs_bot
POSTGRES_PASSWORD={db_password}
DB_POOL_SIZE=10

# ===========================================
# Logging
# ===========================================
LOG_LEVEL=INFO
"""

    with open(".env", "w") as f:
        f.write(env_content)

    # Set secure file permissions (Unix/Linux only)
    if os.name != "nt":  # Not Windows
        try:
            os.chmod(".env", 0o600)
            print("\n✅ .env dosyası güvenli izinlerle (600) oluşturuldu")
        except (PermissionError, NotImplementedError) as e:
            print(f"\n⚠️ Dosya izinleri ayarlanamadı: {e}")
    else:
        print("\n⚠️ Windows sisteminde dosya izinleri manuel olarak ayarlanmalıdır")

    print("✅ .env dosyası oluşturuldu")
    print("\n🔒 Güvenlik: VFS şifresi Fernet ile şifrelenerek saklandı")
    print("📝 Sonraki adımlar:")
    print("   1. .env dosyasının .gitignore'da olduğunu doğrulayın")
    print("   2. Dosya izinlerinin kısıtlı olduğundan emin olun (chmod 600)")
    print("   3. python main.py komutunu çalıştırın")
    print("\n⚠️ ÖNEMLİ GÜVENLİK NOTLARI:")
    print("   - .env dosyasını asla version control'e eklemeyin")
    print("   - Encryption key'leri güvenli bir yerde yedekleyin")
    print("   - Production ortamında .env yerine environment variables kullanmayı düşünün")
    print("   - VFS şifresi otomatik olarak şifrelendi ve uygulama başlangıcında çözülecek")

    # Display encryption key hash for verification (not the actual key)
    key_hash = hashlib.sha256(encryption_key.encode()).hexdigest()[:16]
    print(f"\n🔑 ENCRYPTION_KEY hash (doğrulama için): {key_hash}")
    print("   ⚠️ Key'in tamamı .env dosyasında saklanmıştır. Güvenli bir yere yedekleyin.")


if __name__ == "__main__":
    main()
