#!/usr/bin/env python3
"""Interactive environment setup with encryption support."""

import os
import secrets
from cryptography.fernet import Fernet
from passlib.context import CryptContext


def main():
    print("=== VFS-Bot Environment Setup ===\n")
    print("⚠️  GÜVENLIK UYARISI: Bu script .env dosyası oluşturacak.")
    print("    Dosyayı git'e commit etmemeye dikkat edin!\n")
    
    # Generate encryption key first
    encryption_key = Fernet.generate_key().decode()
    fernet = Fernet(encryption_key.encode())
    
    # Generate other security keys
    api_secret = secrets.token_urlsafe(48)  # 64+ chars for security
    api_key_salt = secrets.token_urlsafe(32)
    vfs_encryption_key = secrets.token_urlsafe(32)
    
    # Get user input
    vfs_email = input("VFS Email: ")
    vfs_password = input("VFS Password: ")
    admin_username = input("Admin Username [admin]: ") or "admin"
    admin_password = input("Admin Password: ")
    
    # Hash admin password for secure storage
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    admin_hash = pwd_context.hash(admin_password)
    
    # Encrypt VFS password
    # Note: VFS password needs to be decryptable for API login
    vfs_password_encrypted = fernet.encrypt(vfs_password.encode()).decode()
    
    # Write .env with encrypted values
    env_content = f"""# VFS-Bot Environment Configuration
# Generated by setup_environment.py
# ⚠️ DO NOT COMMIT THIS FILE TO VERSION CONTROL!

# ===========================================
# VFS Credentials (Encrypted)
# ===========================================
VFS_EMAIL={vfs_email}
# VFS_PASSWORD is encrypted - do not modify manually
VFS_PASSWORD_ENCRYPTED={vfs_password_encrypted}

# ===========================================
# Encryption Keys (CRITICAL - DO NOT SHARE)
# ===========================================
ENCRYPTION_KEY={encryption_key}
VFS_ENCRYPTION_KEY={vfs_encryption_key}

# ===========================================
# API Security
# ===========================================
API_SECRET_KEY={api_secret}
API_KEY_SALT={api_key_salt}

# ===========================================
# Admin Credentials (Password is bcrypt hashed)
# ===========================================
ADMIN_USERNAME={admin_username}
ADMIN_PASSWORD={admin_hash}

# ===========================================
# Environment
# ===========================================
ENV=production

# ===========================================
# Database
# ===========================================
DATABASE_PATH=vfs_bot.db
DB_POOL_SIZE=10

# ===========================================
# Logging
# ===========================================
LOG_LEVEL=INFO
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    # Set secure file permissions (Unix only)
    try:
        os.chmod(".env", 0o600)
        print("\n✅ .env dosyası güvenli izinlerle (600) oluşturuldu")
    except OSError:
        print("\n⚠️ Dosya izinleri ayarlanamadı (Windows?)")
    
    print("✅ .env dosyası oluşturuldu")
    print("\n📝 Sonraki adımlar:")
    print("   1. .env dosyasını .gitignore'a eklediğinizden emin olun")
    print("   2. python main.py komutunu çalıştırın")
    print("\n⚠️ ÖNEMLİ: encryption_key'i güvenli bir yerde yedekleyin!")
    print(f"   ENCRYPTION_KEY: {encryption_key[:20]}...{encryption_key[-10:]}")


if __name__ == "__main__":
    main()
