#!/usr/bin/env python3
"""Interactive environment setup with enhanced security."""

import getpass
import os
import secrets

from cryptography.fernet import Fernet
from passlib.context import CryptContext


def main():
    print("=== VFS-Bot Environment Setup ===\n")
    print("⚠️  GÜVENLIK UYARISI: Bu script .env dosyası oluşturacak.")
    print("    Dosyayı git'e commit etmemeye dikkat edin!")
    print("    .env dosyası hassas bilgiler içerir ve .gitignore'da olmalıdır.\n")

    # Generate encryption key first
    encryption_key = Fernet.generate_key().decode()

    # Generate other security keys
    # token_urlsafe(48) generates 48 bytes = 64 base64 characters
    api_secret = secrets.token_urlsafe(48)  # 64 character output
    api_key_salt = secrets.token_urlsafe(32)  # 43 character output
    vfs_encryption_key = secrets.token_urlsafe(32)  # 43 character output

    # Get user input
    vfs_email = input("VFS Email: ")
    vfs_password = getpass.getpass("VFS Password: ")
    admin_username = input("Admin Username [admin]: ") or "admin"
    admin_password = getpass.getpass("Admin Password: ")

    # Hash admin password for secure storage
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    admin_hash = pwd_context.hash(admin_password)

    # Write .env file
    # Note: VFS_PASSWORD is stored in plain text because the application needs it
    # for VFS API authentication. The .env file itself should be protected with
    # file permissions and never committed to version control.
    env_content = f"""# VFS-Bot Environment Configuration
# Generated by setup_environment.py
# ⚠️ DO NOT COMMIT THIS FILE TO VERSION CONTROL!
# This file contains sensitive credentials and should be in .gitignore

# ===========================================
# VFS Credentials
# ===========================================
VFS_EMAIL={vfs_email}
# Note: VFS_PASSWORD is stored in plain text as required by the application
# Protect this file with appropriate file permissions (600)
VFS_PASSWORD={vfs_password}

# ===========================================
# Encryption Keys (CRITICAL - DO NOT SHARE)
# ===========================================
# Used for encrypting sensitive data in the database and sessions
ENCRYPTION_KEY={encryption_key}
VFS_ENCRYPTION_KEY={vfs_encryption_key}

# ===========================================
# API Security
# ===========================================
# 64-character secret key for JWT token signing
API_SECRET_KEY={api_secret}
# 43-character salt for API key hashing
API_KEY_SALT={api_key_salt}

# ===========================================
# Admin Credentials
# ===========================================
ADMIN_USERNAME={admin_username}
# Password is bcrypt hashed for secure storage
ADMIN_PASSWORD={admin_hash}

# ===========================================
# Environment
# ===========================================
ENV=production

# ===========================================
# Database
# ===========================================
DATABASE_PATH=vfs_bot.db
DB_POOL_SIZE=10

# ===========================================
# Logging
# ===========================================
LOG_LEVEL=INFO
"""

    with open(".env", "w") as f:
        f.write(env_content)

    # Set secure file permissions (Unix/Linux only)
    if os.name != "nt":  # Not Windows
        try:
            os.chmod(".env", 0o600)
            print("\n✅ .env dosyası güvenli izinlerle (600) oluşturuldu")
        except (PermissionError, NotImplementedError) as e:
            print(f"\n⚠️ Dosya izinleri ayarlanamadı: {e}")
    else:
        print("\n⚠️ Windows sisteminde dosya izinleri manuel olarak ayarlanmalıdır")

    print("✅ .env dosyası oluşturuldu")
    print("\n📝 Sonraki adımlar:")
    print("   1. .env dosyasının .gitignore'da olduğunu doğrulayın")
    print("   2. Dosya izinlerinin kısıtlı olduğundan emin olun (chmod 600)")
    print("   3. python main.py komutunu çalıştırın")
    print("\n⚠️ ÖNEMLİ GÜVENLİK NOTLARI:")
    print("   - .env dosyasını asla version control'e eklemeyin")
    print("   - Encryption key'leri güvenli bir yerde yedekleyin")
    print("   - Production ortamında .env yerine environment variables kullanmayı düşünün")
    print(f"\n🔑 ENCRYPTION_KEY (yedekleyin): {encryption_key[:20]}...{encryption_key[-10:]}")


if __name__ == "__main__":
    main()
